In [27]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
# STEP 1: Initialize the weight matrix (20x20x400)
n_cells = 20
W_Mat_mat_size = n_cells ** 2
W_Mat = np.zeros(((n_cells, n_cells, W_Mat_mat_size)))

# Create a 20x20 matrix where each element represents an index value
PC_sheet = np.arange(n_cells * n_cells).reshape(n_cells, n_cells)

In [29]:
# STEP 2: Assign values to W_Mat based on PC_sheet
for row_index in range(n_cells):  # Iterate over rows
    for col_index in range(n_cells):  # Iterate over columns
        for k in range(W_Mat_mat_size):  # Iterate over layers
            # If PC_sheet[row_index, col_index] matches the layer index k
            if PC_sheet[row_index, col_index] == k:
                W_Mat[row_index, col_index, k] = k  # Set the value at the matching index


In [52]:
# STEP 3: Update the weights for each place cell and its neighbors for all layers (k=1 to 400)
for layer in range(W_Mat_mat_size):  # Iterate through all layers
    for row_index in range(n_cells):  # Iterate over rows
        for col_index in range(n_cells):  # Iterate over columns
            
            # Set the center cell's weight to 1 if PC_sheet[row_index, col_index] matches the current layer k
            if PC_sheet[row_index, col_index] == layer:
                W_Mat[row_index, col_index, layer] = 1  # Center cell for the current layer

                # Update the neighbors' weights to 0.5 (if within bounds)
                if row_index > 0:  # Above (not out of bounds)
                    W_Mat[row_index - 1, col_index, layer] = 0.5
                if row_index < n_cells - 1:  # Below (not out of bounds)
                    W_Mat[row_index + 1, col_index, layer] = 0.5
                if col_index > 0:  # Left (not out of bounds)
                    W_Mat[row_index, col_index - 1, layer] = 0.5
                if col_index < n_cells - 1:  # Right (not out of bounds)
                    W_Mat[row_index, col_index + 1, layer] = 0.5

In [62]:
# Initialize a 20x20 sensory input matrix with zeros
sensory_input = np.zeros((20, 20))

# Set the value at position (5, 5) to 1
sensory_input[5, 5] = 1
print(sensory_input)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [40]:
# STEP 5: Initialize an empty output array to store results
output = np.zeros((n_cells, n_cells))